### ISSUE TITLE
Max migration file computes incorrect max-migration, in case earlier migrations before installing the library have custom names, not starting with numbers.

### ISSUE THREAD

**Issue by shikhart98** [adamchainz/django-linear-migrations#161]
### Python Version

3.8

### Django Version

2.2.5

### Package Version

2.3.0

### Description

Max migration file computes incorrect max-migration, in case earlier migrations before installing the library have custom names, not starting with numbers.

Example: 

- app
  - migrations
  | - 001.py
  | - 002.py
  | - custom_migration_name.py
  | - 003.py

in above migration folder actual dependency chain is: `001 -> 002 -> custom_migration_name -> 003` 

But when I am generating max migration file here I am getting `custom_migration_name` value over there, when my actual latest migration is `003`.

**Comment by shikhart98** [comment]
@adamchainz Updated the description.

**Comment by adamchainz** [comment]
Is this when you use `create_max_migration_files`, or later when you use `makemigrations`?

**Comment by shikhart98** [comment]
When I use `create_max_migration_files`.

**Comment by shikhart98** [comment]
@adamchainz any update on this?

**Comment by adamchainz** [comment]
Currently we use `max(migration_details.names)` in a couple places to find the latest migration. I guess to be strictly correct, we need to change to using Django's `MigrationLoader` class to build the migration graph, when we can detect the final migration. This would also let us detect conflicts where there are multiple leaf migrations, like `migrate` does, by calling the loader's `detect_conflicts()` method.
