### ISSUE TITLE
Check dlm.E001 behaviour for detecting presence of migrations does not match create-max-migration-files behaviour

### ISSUE THREAD

**Issue by ahumeau** [adamchainz/django-linear-migrations#20]
Hi Adam,

First thank you for this package, it solves a problem that I have been having for some time. I am excited to try it out.

The inconsistency was introduced by 0f3741cb83020a25960f0832ca4f7bf355395ac6 .

`create-max-migration-files` checks if `len(migration_details.names) > 0`, the check does not.

I am not opening a PR because I want to know your opinion on wether or not it would be a better solution to move that check in `MigrationDetails.has_migrations` instead of just adding it in `check_max_migration_files`.

**Comment by adamchainz** [comment]
I feel like I had a reason at the time why I didn't push that check into `has_migrations`, but I can't remember why. Let's do it and see what breaks.
