### ISSUE TITLE
Unable to create merge migration

### ISSUE THREAD

**Issue by lukashambsch** [adamchainz/django-linear-migrations#239]
### Python Version

3.9.2

### Django Version

3.2.15

### Package Version

2.6.0

### Description

When running `./manage.py makemigrations --merge`, I'm receiving the `dlm.E005` error:

```
(dlm.E005) Conflicting migrations detected - multiple leaf nodes detected for these apps:
...
HINT: Fix the conflict, e.g. with './manage.py makemigrations --merge'.
```

I wouldn't expect to see that error when trying to create the merge migration. To get around the issue I did the following:

1. Commented `django_linear_migrations` in `INSTALLED_APPS`.
2. Ran `./manage.py makemigrations --merge`.
3. Uncommented `django_linear_migrations` in `INSTALLED_APPS`.

**Comment by adamchainz** [comment]
You can use [`--skip-checks`](https://docs.djangoproject.com/en/4.1/ref/django-admin/#cmdoption-skip-checks) to bypass the check as a one-off. We could update the hint to add `--skip-checks`.

Presumably you only encountered this situation once? Also did you need to run `makemigrations --merge` as part of installing django-linear-migrations, or in some other situation?

**Comment by lukashambsch** [comment]
> You can use [`--skip-checks`](https://docs.djangoproject.com/en/4.1/ref/django-admin/#cmdoption-skip-checks) to bypass the check as a one-off. We could update the hint to add `--skip-checks`.
> 
> Presumably you only encountered this situation once? Also did you need to run `makemigrations --merge` as part of installing django-linear-migrations, or in some other situation?

Thanks, `--skip-checks` works.

I've encountered it multiple times in situations other than when installing django-linear-migrations.

**Comment by adamchainz** [comment]
Please give more info - I'd like to see if there is more we could do. You shouldn't be seeing multiple leaf nodes if correctly using the package.

**Comment by adamchainz** [comment]
#240 improved the suggested command

**Comment by lukashambsch** [comment]
Sorry for the slow response. I missed the notifications for your replies. Thanks for improving the suggested command.

It's possible we're using the package incorrectly. I'll describe our situation, a lot of which is caused by an unproductive, temporary development workflow.

We have two branches, which we'll call prod and stage. The stage branch has everything that is in the prod branch, but the prod branch doesn't always have everything in the stage branch. In order to keep the stage branch up-to-date with prod, we merge prod back into stage anytime changes are merged into prod.

Consider the two branches in the following stage:

**prod**
0001
0002
0003

**stage**
0001
0002
0003
0004_A

A PR pointed at the prod branch has migration 0004_B. When that is merged, we merge prod back down into stage, causing a conflict in the max migration file. We resolve that conflict so that 0004_B is the max migration. At that point, when I run `./manage.py showmigrations`, I receive a message noting that I need to run `makemigrations` in order to generate a merge migration. But when I try to run the `makemigrations --merge` command, I receive that same message.

I hope that all makes sense. The situation we're in right now is convoluted so let me know if you have any questions.

**Comment by adamchainz** [comment]
Yeah, you're using an incompatible Git workflow. In order to use linear migrations, you need to be using a linear git history strategy.

Stop making commits on your prod branch and merging them "backwards" into stage. It will make many things about deployments easier, not just the migrations.
