### ISSUE TITLE
Not handling squashes well.

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-linear-migrations#329]
### Python Version

3.10.12

### Django Version

4.2.11

### Package Version

2.12.0

### Description

When there is a squash and that squash includes the most recent migration django-linear-migrations wants the squash to be the migration mentioned in max_migration.txt

Obviously it doesn't do this when the latest migration is not in the squash.

This is regardless of the current migrations state of the DB. That is because the loader isn't given the connection so it can't tell what has been applied which leads it to conclude nothing has been applied and thus all squashes can be used.

**Comment by adamchainz** [comment]
I guess we could override `squashmigrations` to also update `max_migration.txt` files. Or, maybe we can load the graph with `MigrationLoader(replace_migrations=False)`.

Do you have any sense of which would be better, or even time to make a PR?

**Comment by tolomea** [comment]
replace_migrations=False leads to multiple heads which creates further problems
having the squashes in the max_migrations files seems to be otherwise harmless, so maybe having squash update max_migrations is the best path
