### ISSUE TITLE
Migration executed out of order despite dependency

### ISSUE THREAD

**Issue by Darek07** [adamchainz/django-linear-migrations#369]
### Python Version

3.11

### Django Version

4.2.17

### Description

In my Django app, I have two modules with migrations. One migration in the first module is dependent on a migration from the second module. However, when running `python manage.py migrate`, the migration from the first module executed before its dependent migration from the second module.

**Comment by adamchainz** [comment]
That doesn't sound like a django-linear-migrations issue...? You didn't mention this package at all, and it doesn't touch the actual execution of migrations anyway.

**Comment by Darek07** [comment]
It's okay. I just wanted to ensure the issue wasn't with that package. I actually didn't know it doesn't affect migration execution—thanks for clarifying!
