### ISSUE TITLE
It'd be handy if create-max-migration-files had a flag to rewrite them all.

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-linear-migrations#79]
As a recovery from stuff like merge commits not getting recorded.
Obviously I can achieve the same effect by just deleting them first, but it'd be easier if there were a flag.

**Comment by adamchainz** [comment]
`create-max-migration-files --recreate-all` ?

**Comment by tolomea** [comment]
works for me

**Comment by adamchainz** [comment]
Released in 2.0.0 , along with renaming the commands to remove dashes!

**Comment by tolomea** [comment]
Cool, thank you
