### ISSUE TITLE
Rebases the wrong migration when merging branches

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-linear-migrations#80]
When merging a branch (e.g. main) into the current one I would expect the current branches migrations to rebase on top of the incoming branches ones, similar to if you rebase onto main instead of merging main. However instead it rebased the migrations in main. I suspect this is because ours and theirs are reversed in rebases vs merges.

**Comment by tolomea** [comment]
is there currently a work flow for merges?

**Comment by adamchainz** [comment]
No, nothing currently. I always rebase so it doesn't affect me.

**Comment by dmitrysleptsov** [comment]
@adamchainz , I found myself in the same situation as I'm mostly using `git merge` command. What do you think about moving `find_migration_names` function inside `Command` [here](https://github.com/adamchainz/django-linear-migrations/blob/main/src/django_linear_migrations/management/commands/rebase_migration.py#L179). It would allow to simply inherit the class and add any custom logic to deal with `git merge` ourselves.

I can prepare a PR

**Comment by adamchainz** [comment]
Released in 2.8.0, thanks @dmitrysleptsov 🎉
