### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by tolomea** [adamchainz/django-linear-migrations#84]
When it updates dependencies it uses `'` instead of the black preferred `"` is there a way to change this?

**Comment by adamchainz** [comment]
This annoys me to. The format comes from `ast.unparse`, which uses a default repr-like style. I looked into running black, if installed, on the output, but didn't get far. IIRC I couldn't spot how black's API could be run interactively whilst respecting the user's settings for it.

Also some people, myself included, run black outside of their virtualenv, through e.g. pre-commit. So we couldn't import and use it.

The workflow I currently use is `manage.py rebase-migration` then `pre-commit run`. It's a good idea to use `pre-commit run` (or whatever your pre-commit hooks do) when editing commits during a rebase anyway, as git does not run pre-commit hooks for such commits (annoyingly).

**Comment by tolomea** [comment]
was just about to comment on the pre-commit + rebase part of this

**Comment by tolomea** [comment]
I'm already overriding makemigrations, I wonder what it'd take for me to override rebase-migration and run black, obvs since we control the environment, so it's much easier for me to do that just for us, than for you to do it for everyone

**Comment by adamchainz** [comment]
Try it out and let me know how it goes

Personally I am moving towards pre-commit.ci which will autopush black fixes on PR's, so the bother will be minimized.

**Comment by tolomea** [comment]
oh that's nice, pre-commit isn't exactly CI friendly anyway

**Comment by tolomea** [comment]
since I know our developers will always have black pathed this works for me
```
import subprocess

from django.conf import settings
from importlib import import_module

# this is why you shouldn't put a - in a Python file name
module = import_module("django_linear_migrations.management.commands.rebase-migration")


class Command(module.Command):
    def handle(self, *args, **kwargs):
        super().handle(*args, **kwargs)
        subprocess.run(["black", settings.BASE_DIR])
```
in our own `management/commands/rebase-migration.py`

**Comment by adamchainz** [comment]
best to use `check=True` in the `subprocess.run` call :)

**Comment by adamchainz** [comment]
#191 made `rebase_migration` run `black` on edited migrations, just like Django does now, so this is no longer an issue.
